# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "other"
manifest_version = 3
name = "polyfill-service-rs"
# dev
service_id = "06FSzBcnfHpOjSqXwzOxvy"
# qa
# service_id = "4cUBTkiSVlJnR8JPnLvt85"
# prod
# service_id = "3AfcolkTD4KUfkrKGIYZ4T"

[scripts]
  build = "cargo build --bin service --release --target wasm32-wasi --color always -p service && cp target/wasm32-wasi/release/service.wasm bin/main.wasm"

[local_server]
  [local_server.config_stores]
    [local_server.config_stores.toppops_config]
      format = "inline-toml"
    [local_server.config_stores.toppops_config.contents]
      "datacenters" = "ACC MAD CHI BOG EZE LGB JNB HEL FJR QPG TYO PER AKL"