# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["me@jakechampion.name"]
description = "polyfill.io cdn implemented in javascript"
language = "javascript"
manifest_version = 2
name = "polyfill-service-c-at-e"

[local_server.backends.v3_eu]
url = "http://localhost:8080"
# url = "https://origami-polyfill-service-eu.herokuapp.com"
# override_host = "origami-polyfill-service-eu.herokuapp.com"
[local_server.backends.v3_us]
url = "http://localhost:8080"
# url = "https://origami-polyfill-service-us.herokuapp.com"
# override_host = "origami-polyfill-service-us.herokuapp.com"

[local_server.object_store]
bodies = []
headersAndStatus = []

[setup.backends.v3_eu]
address = "origami-polyfill-service-eu.herokuapp.com"
port = 443

[setup.backends.v3_us]
address = "origami-polyfill-service-us.herokuapp.com"
port = 443
